django_1/django_1/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path("myApp/", include("myApp.urls")),
    path("posts/", include("posts.urls")),
    path("user/", include("user.urls")),
    path('about/', views.about),
    path('', views.homepage),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_1/myApp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("todos/", views.todos, name="Todos")
]

django_1/posts/urls.py
from django.urls import path, include
from . import views

app_name = 'posts'

urlpatterns = [
    path("", views.posts_list, name='list'),
    path("new-post/", views.post_new, name='new-post'),
    path("<slug:slug>", views.post_page, name='page'),
]

django_1/user/urls.py
from django.urls import path, include
from . import views

app_name = 'user'

urlpatterns = [
    path('register/',views.registration, name='register'),
    path('login/',views.signIn, name='login'),
    path("logout/",views.signOut, name='logout')

]

django_1/myApp/models.py
from django.db import models

# Create your models here.

class TodoItem(models.Model):
    title = models.CharField(max_length=200)
    completed = models.BooleanField(default=False)

django_1/posts/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    def __str__(self):
        return self.title

django_1/user/models.py
from django.db import models

# Create your models here.

class useRegistration(models.Model):
    firstName = models.TextField(max_length=50)
    lastName = models.TextField(max_length=50)
    email = models.EmailField()
    password = models.CharField()
    rePassword = models.CharField()

    def __str__(self):
        return self.title

django_1/django_1/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

django_1/myApp/views.py
from django.shortcuts import render 
from .models import TodoItem

# Create your views here.
def home(request):
    return render(request, "home.html")

def todos(request):
     items = TodoItem.objects.all()
     return render(request, "todos.html", {"todos": items})

django_1/posts/views.py
from django.shortcuts import render
from .models import Post
from django.contrib.auth.decorators import login_required

# Create your views here.
def posts_list(request):
    posts = Post.objects.all().order_by('-date')
    return render(request, 'posts/posts_list.html', {'posts':posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post':post})

@login_required(login_url='/user/login/')
def post_new(request):
    return render(request, 'posts/post_new.html')

django_1/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.
def registration(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            login(request, form.save())
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, 'users/register_page.html', {"form": form})

def signIn(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            if "next" in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect("posts:list")
    else:
        form = AuthenticationForm(request.POST)
        return render(request, 'users/login_page.html', {"form": form})
def signOut(request):
    if request.method =="POST":
        logout(request)
        return redirect('user:login')

django_1/myApp/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
      {% block title %}
        Django App
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">My Django App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
  </body>
</html>

django_1/myApp/templates/home.html
{% extends "base.html" %} {%block title%} Home Page {% endblock %}
{% block content %}
<p>This is the Home page</p>
{% endblock %}

django_1/myApp/templates/todos.html
{% extends "base.htmL" %} {% block content %}
<h1>Todo List</h1>
<ul>
{% for todo in todos %}
<li>
{{ todo.title }}: {% if todo.completed %}Completed{% else %}Not completed {% endif %}
</li>
{% endfor %}
</ul>
{% endblock %}

django_1/posts/templates/posts/post_new.html
{% extends 'layout.html' %}

{%block title %}
    New Post
{% endblock %}

{% block content %}
<h1>New Post</h1>
{% endblock %}

django_1/posts/templates/posts/post_page.html
{% extends 'layout.html' %}

{%block title %}
    {{post.title}}
{% endblock %}

{% block content %}
<section>
    <h1>{{post.title}}</h1>
    <p>{{post.date}}</p>
    <p>{{post.body}}</p>
    <img src={{post.banner.url}} alt = {{post.title}} class="banner">/</img>
</section>
{% endblock %}

django_1/posts/templates/posts/posts_list.html
{% extends 'layout.html' %}

{%block title %}
    Posts
{% endblock %}

{% block content %}
<section>
    <h1>Posts</h1>
    {% for post in posts %}
    <article class="post">
        <h2>
            <a href = "{% url 'posts:page' slug=post.slug %}">
            {{post.title}}
            </a>
        </h2>
        <p>{{post.date}}</p>
        <p>{{post.body}}</p>
    </article>
    {% endfor %}
</section>
{% endblock %}

django_1/register/templates/register/register_page.html
{% extends 'layout.html' %}

{%block title %}
    Register Page
{% endblock %}

{% block content %}
    <h1>Register Page</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {%  csrf_token %}
        {{form}}
        <button>Submit</button>
    </form>
{% endblock %}

django_1/templates/about.html
{% extends 'layout.html' %}

{%block title %}
    About
{% endblock %}

{% block content %}
    <h1>About</h1>
    <p>Check out my <a href="/">Home</a> page.<p>
{% endblock %}

django_1/templates/home.html
{% extends 'layout.html' %}

{%block title %}
    Home
{% endblock %}

{% block content %}
    <h1>home</h1>
    <p>Check out my <a href="/about">About</a> page.<p>
{% endblock %}

django_1/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
            Django App
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"  rel="stylesheet" />
    <script src="{% static 'js/main.js' %}" defer></script>
</head>
<body>
   <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">My Django App</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Contact</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:list' %}">Posts</a>
          </li>
          
          {%if user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'posts:new-post' %}">New Post</a>
          </li>
          <li class="nav-item">
            <form class="nav-link" action="{% url 'user:logout' %}" method='post'>
              {% csrf_token %}
              <button title="User Logout">Logout</button>
            </form>
          </li>
          {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:register' %}">Register</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'user:login' %}">login</a>
            </li>
          {% endif %}
          
      </ul>
      </div>
    </nav>
    <div class="container">{% block content %} {% endblock %}</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js" ></script>
</body>
</html>

django_1/user/templates/users/login_page.html
{% extends 'layout.html' %}

{%block title %}
    Login Page
{% endblock %}

{% block content %}
    <h1>Login Page</h1>
    <form class="form-with-validation" action="/user/login/" method="post">
        {%  csrf_token %}
        {{form}}
        {% if request.GET.next %}
            <input type='hidden' name='next' value='{{request.GET.next }}' />
        {% endif %}
        <button>Submit</button>
    </form>
{% endblock %}

django_1/user/templates/users/register_page.html
{% extends 'layout.html' %}

{%block title %}
    Register Page
{% endblock %}

{% block content %}
    <h1>Register Page</h1>
    <form class="form-with-validation" action="/user/register/" method="post">
        {%  csrf_token %}
        {{form}}
        <button>Submit</button>
    </form>
{% endblock %}